version: "3.4"

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: xyz
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - task_list_db_data:/var/lib/mysql
    ports:
      - target: 3306
        published: 3306
        protocol: tcp

volumes:
  task_list_db_data:
